Add option to read/write ISO8859-1/-2 encoded fields
MediaArea/BWFMetaEdit pull request #233
Opened 2022-07-11 07:23 UTC by g-maxime

Fixes #229

2022-07-11 21:27 UTC, g-maxime commented
> @g-maxime, can you link to a build for testing?

https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20220711/
https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20220711/

2022-09-08 18:36 UTC, MarcosSueiro commented
Love the idea of having UTF-8 as default. Jerôme, are you saying that currently this is the default BWFME encoding as well on Windows? What is the Linux behaviour?

2022-09-08 20:04 UTC, JeromeMartinez commented
@MarcosSueiro I was sure that in the past it was local code page on windows so not UTF8 but I see UTF8 now...

For non Windows local codename is nowadays UTF8 so it is sure that it is UTF8 for them.

2022-11-08 15:55 UTC, JeromeMartinez requested changes
Le's try another approach.

We have an edit box similar to TimeReference for selecting the codepage. CountryCode/LanguageCode/Dialect are untouched / not diplayed for the moment, only a select box with some codepages.

The [code page identifier list](https://learn.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) shows that there are actually more difficulties, let's support:
437 (the default in the US)
850 (the default in some western Europe countries)
858 (850 + €)
1252
28591 (iso-8859-1)
28592 (iso-8859-2)
65001 (UTF-8)

If CSET is changed, all other non XML fields change their encoding during save of the file.
As for other chunks, possibility to remove it (except if "write CSET chunk" option, it becomes "reset it")

If there is a CSET codepage not supported (except if "ignore encoding stored...") --> error, file rejected, and we'll see...
If there is no CSET and UTF-8 selected and a malformed UTF-8 string --> error, file rejected, saying to use a different codepage...
If there is a CSET chunk, it has the priority over the prefs (except if "ignore encoding stored...")

Preferences:
for the radio button with codepage
Add "If there is not CSET chunk or if it should be ignored, consider non ASCII bytes as:"
Then the list above + "system default encoding"
for system default encoding, read it on Windows from [GetAPC](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getacp) and on other platforms check that this is UTF-8 (I doubt that nowadays OS have something else)
Default with UTF-8

No warning about non-ASCII chars

2022-12-15 19:24 UTC, JeromeMartinez commented
[Updated dev snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20221215/).

2023-01-29 00:56 UTC, JeromeMartinez approved these changes

2023-01-29 00:56 UTC, merged

2023-01-29 14:17 UTC, MarcosSueiro commented
This is very exciting. Is this feature included in the current official release?

2023-01-29 14:22 UTC, JeromeMartinez commented
@MarcosSueiro we'll do an official release in the next days, in the meantime it is in the latest [snapshots](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/).
Please test :).

2023-01-30 14:11 UTC, JeromeMartinez commented
> Is this feature included in the current official release?

[now](https://mediaarea.net/BWFMetaEdit) (v23.01).